from PyQt6 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(428, 414)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 391, 141))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 97, 81, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 100, 280, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 280, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(300, 47, 81, 26))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 181, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 181, 18))
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 180, 141, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 111, 22))
        self.radioButton.setObjectName("s")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 65, 95, 22))
        self.radioButton_2.setObjectName("l")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 100, 151, 22))
        self.radioButton_3.setObjectName("b")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 135, 151, 22))
        self.radioButton_4.setObjectName("ls")
        self.radioButton_5 = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 170, 151, 22))
        self.radioButton_5.setObjectName("bs")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 190, 231, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 250, 131, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 290, 231, 20))
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 160, 391, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 250, 131, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Select files"))
        self.pushButton_2.setText(_translate("MainWindow", "Open folder"))
        self.pushButton.setText(_translate("MainWindow", "Open file"))
        self.label.setText(_translate("MainWindow", "Select input image folder"))
        self.label_2.setText(_translate("MainWindow", "Select output folder"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Select method"))
        self.radioButton.setText(_translate("MainWindow", "SRGAN x4"))
        self.radioButton_2.setText(_translate("MainWindow", "Lanczos x4"))
        self.radioButton_3.setText(_translate("MainWindow", "Bicubic x4"))
        self.radioButton_4.setText(_translate("MainWindow", "Lanczos + SRGAN"))
        self.radioButton_5.setText(_translate("MainWindow", "Bicubic + SRGAN"))
        self.pushButton_3.setText(_translate("MainWindow", "START"))
        self.label_3.setText(_translate("MainWindow", "Waiting..."))
        self.label_4.setText(_translate("MainWindow", "Completed in: ..."))
        self.pushButton_4.setText(_translate("MainWindow", "CANCEL"))
